baseURL = 'https://zinmik.github.io/math-blog/'
locale = 'en-us'
title = 'Mathematical Adumbrations'
theme = "github.com/ananthb/jughead"
copyright = "Mikulas Zindulka"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$'], ['\[', '\]']]
          inline = [['$', '$'], ['\(', '\)']]

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params.giscus]
repo = "zinmik/math-blog"
repoId = "R_kgDOU-0p-A"
category = "Announcements"
categoryId = "DIC_kwDOU-0p-M4DHN4A"
mapping = "pathname"
strict = "0"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "bottom"
theme = "preferred_color_scheme"
lang = "en"

[[menus.main]]
name = 'About'
pageRef = 'about'
weight = 10