baseURL = 'https://zinmik.github.io/math-blog/'
locale = 'en-us'
title = 'Mathematical Adumbrations'
theme = "github.com/ananthb/jughead"

[markup.goldmark.extensions.passthrough]
enable = true

[markup.goldmark.extensions.passthrough.delimiters]
block = [['$$', '$$']]
inline = [['$', '$']]

[caches]
  [caches.images]
    dir = ':cacheDir/images'